CONTRIBUTORS.md
Scripts/hello_world_german.js

Hello World in German!

---

CONTRIBUTORS.md
Scripts/hello_world_kannada.py

Python Script for Hello World in one of India's languages Kannada. Please accept my PR.

Add Hello World in Kannada

---

CONTRIBUTORS.md
Scripts/hello_world_telugu.js

I have added Telugu version of Hello World in scripts folders .

Added Telugu version of hello world in scripts folder

---

CONTRIBUTORS.md
hello_world_inohime.go

Hello World in English (Go)

---

CONTRIBUTORS.md
Scripts/hello_world_poveii.js

I decided to make a Hello World different, adding this code on index.html, it will show you my Hello World!
_Olá, mundo!_

My contribution with hello_world_poveii.js

---

CONTRIBUTORS.md
Scripts/hello_world_flawlesslys.sh

@calixtocarolina Hi Carolina, PR to add my contribution in bash language.
Please add the 'hacktoberfest-accepted' label & merge my PR if ok :)
Thanks!

Add hello_world_flawlesslys.sh

---

Scripts/hello_world_sanskrit.js

I have added hello world in sanskrit language in scripts folder .

Added hello world in Sanskrit language

---

CONTRIBUTORS.md
Scripts/hello_world_00sukhjeet00.rs

Add hello world for rust language

rust language

---

CONTRIBUTORS.md
Scripts/hello_world_mansi-singla-31215.cpp

Hey @calixtocarolina , can you pls review this PR and merge it under Hacktoberfest label .

Added Hello World written in Hindi

---

CONTRIBUTORS.md
Scripts/hello_world_anishghimire603.js

Hey, I have added hello world in my native Language, in Nepali Language, Would you kindly review my PR and merge it. [😊](https://emojipedia.org/smiling-face-with-smiling-eyes/)

Added Hello World! in Nepali in JS

---

CONTRIBUTORS.md
Scripts/hello_world_Prachi-22-81.java

Hello @calixtocarolina , can you please review this PR and merge it under Hacktoberfest label .

Added new script file and updated contributions.md

---

.vscode/settings.json
CONTRIBUTORS.md
Scripts/hello_world_CydaCode.js

I created a script of "Hello World" in my native language called "Igbo"

Hello World in Igbo language by Cynthia Nwankwo

---

CONTRIBUTORS.md
Scripts/hello_world_Nwekegoddy.js

I'm from the southern part of  Nigeria where oil flows like milk.

Celebrating Diversity

---

Scripts/hello_world_bhoomitri4.sh

Hello World!(Hindi) in Bash

---

Scripts/hello_world_assamese.js

The programming language used is javascript.

Hello World in Assamese

---

CONTRIBUTORS.md

Added the details following the conventions mentioned in README.md

Added the details in contributors.md

---

CONTRIBUTORS.md
Scripts/hello-world_bhoomitri4.jl

Hello World!(Hindi) in Julia. please merge the PR. Thank you!!

Hello World!(Hindi) in Julia

---

CONTRIBUTORS.md
Scripts/hello_world_t-moennich.ts

Add hello world in TypeScript and german

---

Scripts/hello_world_greepthesheep.cs
Scripts/hello_world_greepthesheep.py

Create a Hello World in French in Python and C#.
I'm already in the Contributors list so that's okay

Hello World in French (Python & C#)

---

CONTRIBUTORS.md
Scripts/hello_world_AshishSharma1203.js

Added hello_world_AshishSharma1203.js in the native language i.e Hindi and updated the contribution.md file regarding this.

Added hello_world_AshishSharma1203.js in native language

---

Scripts/hello_world_greepthesheep.as

This is a AngelScript version of my Hello World!
It uses Openplanet's API: Openplanet is an alternative scripting platform for the Trackmania and Maniaplanet creative community.
All details on this website: https://openplanet.dev/

Hello World in French (Openplanet API)

---

CONTRIBUTORS.md
Scripts/hello_world_brumcaroline.rb

Added Hello, World in Dutch using Ruby. :)

My contribution

---

CONTRIBUTORS.md
Scripts/hello_world_zehjulianlp.mcfunction

The programming language is used in Minecraft de develop Datapacks

Added Hello World in german in MCFunction
